# This script generates a simple piece of "fractal music"
# using a cellular automaton, a system of simple rules
# that can produce complex patterns.
# The generated music is saved as a MIDI file.

# First, install the required library in your terminal:
# pip install MIDIUtil

from midiutil import MIDIFile

def generate_cellular_automaton_music():
    """
    Generates music based on a cellular automaton and saves it to a MIDI file.
    """
    # ----- SETTINGS -----
    # The length of the musical piece (in iterations of the automaton)
    num_beats = 120
    # Beats per minute
    tempo = 120
    # The initial state of the automaton (a single 'on' cell)
    initial_state = [0] * 128
    initial_state[64] = 1 # A single 'on' cell in the middle
    
    # Define a simple cellular automaton rule (e.g., Rule 30)
    # This rule determines the next state of a cell based on its neighbors.
    # The patterns generated by this rule are often complex and "fractal-like."
    def apply_rule_30(left, center, right):
        if left == 1 and center == 1 and right == 1: return 0
        if left == 1 and center == 1 and right == 0: return 0
        if left == 1 and center == 0 and right == 1: return 0
        if left == 1 and center == 0 and right == 0: return 1
        if left == 0 and center == 1 and right == 1: return 1
        if left == 0 and center == 1 and right == 0: return 1
        if left == 0 and center == 0 and right == 1: return 1
        if left == 0 and center == 0 and right == 0: return 0

    # ----- MUSIC GENERATION -----
    # Create a MIDI file object
    midi_file = MIDIFile(1)  # One track
    midi_file.addTempo(0, 0, tempo)  # Track 0, at time 0, set tempo

    # Mapping of cellular automaton states to musical notes
    # We'll use a simple major scale for a pleasant sound.
    # Note numbers correspond to MIDI note values (60 is Middle C)
    major_scale = [60, 62, 64, 65, 67, 69, 71] # C Major
    
    current_state = initial_state
    
    # Iterate for the desired number of beats (rows in the automaton)
    for beat in range(num_beats):
        next_state = [0] * 128
        
        # Apply the rule to each cell to get the next state (the next "beat")
        for i in range(1, len(current_state) - 1):
            left = current_state[i-1]
            center = current_state[i]
            right = current_state[i+1]
            next_state[i] = apply_rule_30(left, center, right)
            
        # Translate the new state into musical notes
        for note_index, cell_value in enumerate(next_state):
            if cell_value == 1:
                # Map the cell position to a note in our scale
                note = major_scale[note_index % len(major_scale)]
                
                # Add the note to the MIDI file
                # Track, channel, pitch, time, duration, volume
                midi_file.addNote(0, 0, note, beat, 1, 100) # Play the note for 1 beat at a volume of 100
                
        current_state = next_state

    # ----- SAVE THE MIDI FILE -----
    filename = "fractal_music.mid"
    with open(filename, "wb") as output_file:
        midi_file.writeFile(output_file)
        
    print(f"Music saved to '{filename}'! You can open it with any media player.")


if __name__ == "__main__":
    generate_cellular_automaton_music()
